spring:
  application:
    name: microservice-config-server-consums-ribbon-without-eureka
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/songabao?&useSSL=false&useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=UTF-8
    username: root
    password: root
server:
  port: 8920
mybatis:
  mapper-locations: classpath*:/mybatis/mappers/*.xml
  type-aliases-package: com.microservice.domain
  config-location: classpath:mybatis/mybatis-config.xml

microservice-config-server-production-ribbon-without-eureka:
  ribbon:
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    listOfServers: localhost:8917,localhost:8918,localhost:8919
